# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target '51_cocoapods应用' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 51_cocoapods应用
  pod 'AFNetworking'
  pod 'MBProgressHUD'
end
